[package]
name = "btgc-term-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
btgc-core = { version = "0.1.0", path = "../btgc-core" }
rustc-hash = { version = "2.1.1", features = ["nightly"] }
