[package]
name = "btgc-cart-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
btgc-core = { version = "0.1.0", path = "../btgc-core" }
embedded-io = { version = "0.6.1", features = ["alloc"] }
embedded-io-async = { version = "0.6.1", features = ["alloc"] }
